<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
                ->appendHttpEquiv('Content-Language', 'pt-BR')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
                ->appendHttpEquiv('Cache-Control', 'max-age=31536000; public')
                ->appendHttpEquiv('Last-Modified', gmdate('D, d M Y H:i:s') . " GMT");
        ?>

        <?php echo $this->headTitle('Acácio Vilela - ' . $this->translate('Login'))->setSeparator(' - ')->setAutoEscape(true); ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/app.css')
                ->prependStylesheet($this->basePath() . '/font-awesome/css/font-awesome.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css');
        ?>
        <!--[if IE 7]>
            <link rel="stylesheet" href="/font-awesome/css/font-awesome-ie7.min.css">
        <![endif]-->
        <!--[if lte IE 8]><script language="javascript" type="text/javascript" src="/js/excanvas.min.js"></script><![endif]-->
        <!--[if lt IE 9]>
                <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <?php
        echo $this->headScript()
                ->appendFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->appendFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',));
        ?>
    </head>
    <body>
        <div class="container">
            <?php echo $this->content; ?>
        </div>
        <?php
        echo $this->inlineScript()
                ->appendFile($this->basePath() . '/js/jquery.min.js', 'text/javascript', array('async' => 'async'))
                ->appendFile($this->basePath() . '/js/bootstrap.min.js', 'text/javascript', array('async' => 'async'))
        ;
        ?>  
    </body>
</html>
