<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <?php
        echo $this->headMeta()
                ->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
                ->appendHttpEquiv('Content-Language', 'pt-BR')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
                ->appendHttpEquiv('Cache-Control', 'max-age=31536000; public')
                ->appendHttpEquiv('Last-Modified', gmdate('D, d M Y H:i:s') . " GMT")
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ?>

        <?php echo $this->headTitle('Acácio Vilela - ' . $this->translate('Login'))->setSeparator(' - ')->setAutoEscape(true) ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/font-awesome/css/font-awesome.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>
        <!--[if IE 7]>
            <link rel="stylesheet" href="/font-awesome/css/font-awesome-ie7.min.css">
        <![endif]-->
        <!--[if lte IE 8]><script language="javascript" type="text/javascript" src="/js/excanvas.min.js"></script><![endif]-->
        <!--[if lt IE 9]>
                <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        <!--[if IE 9]>
                <link id="ie9style" href="/backend/css/ie9.css" rel="stylesheet">
        <![endif]-->
        <?php
        echo $this->headScript()
                ->appendFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->appendFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',));
        ?>
    </head>
    <body>
        <div class="container-fluid-full">
            <div class="row-fluid">
                <div class="row-fluid">
                    <div class="login-box">
                        <div class="icons">
                            <a href="<?php echo $this->basePath(); ?>"><i class="halflings-icon home"></i></a>
                            <a href="#"><i class="halflings-icon cog"></i></a>
                        </div>
                        <h2><?php echo $this->translate('Login de Usuário'); ?></h2>
                        <?php echo $this->content; ?>
                    </div>
                </div>
            </div>
        </div>
        <?php
        echo $this->inlineScript()
                ->appendFile($this->basePath() . '/backend/js/jquery-1.9.1.min.js', 'text/javascript', array('async' => 'async'))
                ->appendFile($this->basePath() . '/backend/js/jquery-migrate-1.0.0.min.js', 'text/javascript', array('async' => 'async'))
                ->appendFile($this->basePath() . '/backend/js/jquery-ui-1.10.0.custom.min.js', 'text/javascript', array('async' => 'async'))
                ->appendFile($this->basePath() . '/backend/js/jquery.ui.touch-punch.js', 'text/javascript', array('async' => 'async'))
                ->appendFile($this->basePath() . '/backend/js/modernizr.js', 'text/javascript', array('async' => 'async'))
                ->appendFile($this->basePath() . '/backend/js/bootstrap.min.js', 'text/javascript', array('async' => 'async'))
                ->appendFile($this->basePath() . '/backend/js/jquery.cookie.js', 'text/javascript', array('async' => 'async'))
                ->appendFile($this->basePath() . '/backend/js/fullcalendar.min.js', 'text/javascript', array('async' => 'async'))
                ->appendFile($this->basePath() . '/backend/js/jquery.dataTables.min.js', 'text/javascript', array('async' => 'async'))
                ->appendFile($this->basePath() . '/backend/js/excanvas.js', 'text/javascript', array('async' => 'async'))
                ->appendFile($this->basePath() . '/backend/js/jquery.flot.js', 'text/javascript', array('async' => 'async'))
                ->appendFile($this->basePath() . '/backend/js/jquery.flot.pie.js', 'text/javascript', array('async' => 'async'))
                ->appendFile($this->basePath() . '/backend/js/jquery.flot.stack.js', 'text/javascript', array('async' => 'async'))
                ->appendFile($this->basePath() . '/backend/js/jquery.flot.resize.min.js', 'text/javascript', array('async' => 'async'))
                ->appendFile($this->basePath() . '/backend/js/jquery.chosen.min.js', 'text/javascript', array('async' => 'async'))
                ->appendFile($this->basePath() . '/backend/js/jquery.uniform.min.js', 'text/javascript', array('async' => 'async'))
                ->appendFile($this->basePath() . '/backend/js/jquery.cleditor.min.js', 'text/javascript', array('async' => 'async'))
                ->appendFile($this->basePath() . '/backend/js/jquery.noty.js', 'text/javascript', array('async' => 'async'))
                ->appendFile($this->basePath() . '/backend/js/jquery.elfinder.min.js', 'text/javascript', array('async' => 'async'))
                ->appendFile($this->basePath() . '/backend/js/jquery.raty.min.js', 'text/javascript', array('async' => 'async'))
                ->appendFile($this->basePath() . '/backend/js/jquery.iphone.toggle.js', 'text/javascript', array('async' => 'async'))
                ->appendFile($this->basePath() . '/backend/js/jquery.uploadify-3.1.min.js', 'text/javascript', array('async' => 'async'))
                ->appendFile($this->basePath() . '/backend/js/jquery.gritter.min.js', 'text/javascript', array('async' => 'async'))
                ->appendFile($this->basePath() . '/backend/js/jquery.imagesloaded.js', 'text/javascript', array('async' => 'async'))
                ->appendFile($this->basePath() . '/backend/js/jquery.masonry.min.js', 'text/javascript', array('async' => 'async'))
                ->appendFile($this->basePath() . '/backend/js/jquery.knob.modified.js', 'text/javascript', array('async' => 'async'))
                ->appendFile($this->basePath() . '/backend/js/jquery.sparkline.min.js', 'text/javascript', array('async' => 'async'))
                ->appendFile($this->basePath() . '/backend/js/counter.js', 'text/javascript', array('async' => 'async'))
                ->appendFile($this->basePath() . '/backend/js/retina.js', 'text/javascript', array('async' => 'async'))
                ->appendFile($this->basePath() . '/backend/js/custom.js', 'text/javascript', array('async' => 'async'))
        ;
        ?>  
    </body>
</html>
