<?php $address = $this->address ?>
<?php echo $this->formHidden($address->get('id')); ?>
<div class="row">
    <div class="col-md-8">
        <div class="form-group">
            <?php echo $this->formLabel($address->get('name')); ?>
            <?php echo $this->formText($address->get('name')); ?>
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <?php echo $this->formLabel($address->get('number')); ?>
            <?php echo $this->formText($address->get('number')); ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <div class="form-group">
            <?php echo $this->formLabel($address->get('complement')); ?>
            <?php echo $this->formText($address->get('complement')); ?>
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <?php echo $this->formLabel($address->get('quarter')); ?>
            <?php echo $this->formText($address->get('quarter')); ?>
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <?php echo $this->formLabel($address->get('postalCode')); ?>
            <?php echo $this->formText($address->get('postalCode')); ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <div class="form-group">
            <?php echo $this->formLabel($address->get('city')); ?>
            <?php echo $this->formSelect($address->get('city')); ?>
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <?php echo $this->formLabel($address->get('state')); ?>
            <?php echo $this->formSelect($address->get('state')); ?>
        </div>
    </div>
    <div class="col-md-2">
        <div class="form-group">
            <?php echo $this->formLabel($address->get('country')); ?>
            <?php echo $this->formSelect($address->get('country')); ?>
        </div>
    </div>
</div>


