<?php $professional = $this->professional; ?>
<?php echo $this->formHidden($professional->get('id')); ?>
<div class="row">
    <div class="col-md-8">
        <div class="form-group">
            <?php echo $this->formLabel($professional->get('companyName')); ?>
            <?php echo $this->formText($professional->get('companyName')); ?>
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <?php echo $this->formLabel($professional->get('companyCnpj')); ?>
            <?php echo $this->formText($professional->get('companyCnpj')); ?>
        </div>
    </div>
</div>

<?php $address = $professional->get('address') ?>
<?php echo $this->addressForm($address); ?>

<?php $contact = $professional->get('contact') ?>
<?php echo $this->contactForm($contact); ?>

<div class="row">
    <div class="col-md-4">
        <div class="form-group">
            <?php echo $this->formLabel($professional->get('inDate')); ?>
            <?php echo $this->formText($professional->get('inDate')); ?>
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <?php echo $this->formLabel($professional->get('salary')); ?>
            <div class="input-group">
                <span class="input-group-addon">R$</span>
                <?php echo $this->formText($professional->get('salary')); ?>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <?php echo $this->formLabel($professional->get('otherRevenue')); ?>
            <div class="input-group">
                <span class="input-group-addon">R$</span>
                <?php echo $this->formText($professional->get('otherRevenue')); ?>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <div class="form-group">
            <?php echo $this->formLabel($professional->get('office')); ?>
            <?php echo $this->formSelect($professional->get('office')); ?>
        </div>
    </div>
</div>
</div>
