<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
return array(
    'modules' => array(
//        'ZF2NetteDebug',
        'DoctrineModule',
        'DoctrineORMModule',
        'Application',
        'DtlBase',
        'DtlAdmin',
        'DtlPerson',
        'DtlLocation',
        'DtlOccupation',
        'DtlOffice',
        'DtlUser',
        'DtlTwitter',
    ),
    'module_listener_options' => array(
        'module_paths' => array(
            './module',
            './vendor',
        ),
        'config_glob_paths' => array(
            'config/autoload/{{,*.}global,{,*.}local}.php',
        ),
        'check_dependencies' => true,
    ),
    'service_manager' => array(
        
    ),
);
