<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'DtlOccupation\Form\Fieldset\Occupation'        => __DIR__ . '/src/DtlOccupation/Form/Fieldset/Occupation.php',
  'DtlOccupation\Form\Occupation'                 => __DIR__ . '/src/DtlOccupation/Form/Occupation.php',
  'DtlOccupation\Factory\Occupation'              => __DIR__ . '/src/DtlOccupation/Factory/Occupation.php',
  'DtlOccupation\Controller\OccupationController' => __DIR__ . '/src/DtlOccupation/Controller/OccupationController.php',
  'DtlOccupation\Entity\Occupation'               => __DIR__ . '/src/DtlOccupation/Entity/Occupation.php',
  'DtlOccupation\Module'                          => __DIR__ . '/Module.php',
);
