<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('dtluser/login'));
$login = $form->get('login');
?>
<div class="row">
    <div class="col-lg-4 col-lg-offset-4">
        <div class="user-login-box">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="panel-title">
                        <?php echo $this->translate('Login de Usuário'); ?>
                    </div>
                </div>
                <div class="panel-body">
                    <?php echo $this->form()->openTag($form) ?>
                    <?php echo $this->formElementErrors($login->get('username')) ?>
                    <div class="form-group">
                        <div class="input-group" title="Username">
                            <span class="input-group-addon"><i class="fa fa-user"></i></span>
                            <?php echo $this->formInput($login->get('username')) ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="input-group" title="Password">
                            <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                            <?php echo $this->formInput($login->get('password')) ?>
                        </div>
                    </div>
                    <div class="checkbox">
                        <label class="remember" for="remember">
                            <input type="checkbox" id="remember" /> <?php echo $this->translate('Manter conectado'); ?>
                        </label>
                    </div>

                    <div class="button-login">
                        <?php echo $this->formSubmit($form->get('submit')) ?>
                    </div>

                    <?php if ($this->redirect): ?>
                        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
                    <?php endif ?>
                    <?php echo $this->form()->closeTag() ?>

                    <hr class="divider" />

                    <h5><?php echo $this->translate('Acesse através das redes sociais'); ?></h5>
                    
                    <?php echo $this->dtlSocialButton("Twitter"); ?>
                    <?php echo $this->dtlSocialButton("Facebook"); ?>

                    <a href="<?php echo $this->dtlInstagramUri(); ?>" class="btn btn-primary btn-block"><i class="fa fa-instagram"></i> <?php echo $this->translate('Instagram'); ?></a>
                </div>
                <div class="panel-footer">
                    <p>
                        <?php echo $this->translate('Ainda não possui cadastro?'); ?>
                        <a href="<?php echo $this->url('dtluser/register'); ?>"><?php echo $this->translate('Registre-se aqui'); ?></a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
