<?php
$form = $this->form;
$form->prepare();
$user = $form->get('user');
$person = $user->get('person');
?>
<div class="container">
    <div class="row">
        <div class="user-register is-responsive">
            <div class="col-xs-4 col-xs-offset-3">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?php echo $this->translate('Cadastre-se'); ?></h3>
                    </div>
                    <div class="panel-body">
                        <?php echo $this->form()->openTag($form); ?>    
                        <fieldset>
                            <div class="form-group">
                                <?php echo $this->formLabel($person->get('name')); ?>
                                <?php echo $this->formText($person->get('name')); ?>
                                <?php echo $this->formElementErrors($person->get('name')); ?>
                            </div>
                            <div class="form-group">
                                <?php echo $this->formLabel($user->get('email')); ?>
                                <?php echo $this->formText($user->get('email')); ?>
                                <?php echo $this->formElementErrors($user->get('email')); ?>
                            </div>
                            <div class="form-group">
                                <?php echo $this->formLabel($user->get('username')); ?>
                                <?php echo $this->formText($user->get('username')); ?>
                                <?php echo $this->formElementErrors($user->get('username')); ?>
                            </div>
                            <div class="form-group">
                                <?php echo $this->formLabel($user->get('password')); ?>
                                <?php echo $this->formPassword($user->get('password')); ?>
                                <?php echo $this->formElementErrors($user->get('password')); ?>
                            </div>
                            <div class="form-group">
                                <?php echo $this->formLabel($user->get('passwordVerify')); ?>
                                <?php echo $this->formPassword($user->get('passwordVerify')); ?>
                            </div>
                            <div class="form-group">
                                <?php echo $this->formElement($form->get('security')); ?>
                                <?php echo $this->formElement($form->get('submit')); ?>
                            </div>
                        </fieldset>
                        <?php echo $this->form()->closeTag($form); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>