<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <?php
        echo $this->headMeta()
                ->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
                ->appendHttpEquiv('Content-Language', 'pt-BR')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
                ->appendHttpEquiv('Cache-Control', 'max-age=31536000; public')
                ->appendHttpEquiv('Last-Modified', gmdate('D, d M Y H:i:s') . " GMT")
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ?>

        <?php echo $this->headTitle('Acácio Vilela ' . $this->translate('Admin'))->setSeparator(' - ')->setAutoEscape(true) ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/app.css')
                ->prependStylesheet($this->basePath() . '/font-awesome/css/font-awesome.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>
        <!--[if IE 7]>
            <link rel="stylesheet" href="/font-awesome/css/font-awesome-ie7.min.css">
        <![endif]-->
        <!--[if lte IE 8]><script language="javascript" type="text/javascript" src="/js/excanvas.min.js"></script><![endif]-->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery-ui.min.js', 'text/javascript', array('async' => 'async'))
                ->prependFile($this->basePath() . '/js/jquery.min.js', 'text/javascript', array('async' => 'async'))
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ?>
    </head>
    <body>
        <?php echo $this->partial('layout/menu'); ?>

        <div class="container-fluid">
            <?php echo $this->content; ?>
            <?php echo $this->inlineScript(); ?>                
        </div>

        <?php echo $this->partial('layout/footer'); ?>
    </body>
</html>
