<?php

$current_page = array();

foreach ($this->pages as $page) {
    if (!$page->isActive()) {
        if ($page->getLabel() === 'Home') {
            $current_page[] = '<li><a href="' . $page->getHref() . '"><i class="glyphicon glyphicon-dashboard"></i> ' . $this->translate($page->getLabel()) . '</a> </li> ';
        } else {
            $current_page[] = '<li><a href="' . $page->getHref() . '">' . $this->translate($page->getLabel()) . '</a> </li> ';
        }
    } else {
        if ($page->getLabel() === 'Home') {
            $current_page[] = '<li><i class="glyphicon glyphicon-dashboard"></i> ' . $this->translate($page->getLabel()) . '</li> ';
        } else {
            $current_page[] = '<li class="active">' . $this->translate($page->getLabel()) . '</a></li>';
        }
    }
}

$breadcrumb = implode($current_page);

$company = "VALORIZA";
echo sprintf('<ul class="breadcrumb hidden-print">%s<div class="pull-right">%s</div></ul>', $breadcrumb, $company);
