<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/application.css')
                ->prependStylesheet($this->basePath() . '/css/jquery-ui/smoothness/jquery-ui-1.10.3.custom.min.css')
                ->prependStylesheet($this->basePath() . '/font-awesome/css/font-awesome.min.css')
                ->prependStylesheet($this->basePath() . '/bootstrap/css/bootstrap-theme.css')
                ->prependStylesheet($this->basePath() . '/bootstrap/css/bootstrap.min.css')
        ?>
        <!--[if IE 7]>
            <link rel="stylesheet" href="/font-awesome/css/font-awesome-ie7.min.css">
        <![endif]-->
        <!--[if lte IE 8]><script language="javascript" type="text/javascript" src="/js/excanvas.min.js"></script><![endif]-->
        <?php
        echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/application.js')
                ->prependFile($this->basePath() . '/js/jquery.price.js')
                ->prependFile($this->basePath() . '/js/jquery-masked.js')
                ->prependFile($this->basePath() . '/bootstrap/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.ui.datepicker-pt-BR.js')
                ->prependFile($this->basePath() . '/js/jquery-ui.min.js')
                ->prependFile($this->basePath() . '/js/jquery-2.0.3.min.js')
        ?>
    </head>
    <body>
        <?php echo $this->content; ?>
    </body>
</html>
